name: producingtheology
favicon: null
layout_spectrum: 0.4773957359138876
typography_spectrum: 0.6128642947878689
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Weblog Dedicated to the Theological Study of Technology and the Church
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: engagement
    url: null
    item: b3b06c38-678b-4722-a1bc-d50271916e12
