analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.4773957359138876
title: Weblog Dedicated to the Theological Study of Technology and the Church
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.5
  brandStrength: 0
  rhythmicContrast: 0.5
  brandColors: []
  lightness: 0.5
purpose:
  - name: engagement
    url: null
    item: b3b06c38-678b-4722-a1bc-d50271916e12
favicon: null
name: producingtheology
typography_spectrum: 0.6128642947878689
